server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: CWLx.88649981
mybatis:
  mapper-locations: classpath:mapper/*.xml   # 今天用注解，可不建 xml
  type-aliases-package: com.example.demo.entity

